name: Test Implyzer

on:
  push:
    paths:
      - 'Implyzer/**'
      - 'Implyzer.Tests/**'
      - '.github/workflows/test.yml'
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: ubuntu-latest
    
    env:
      SolutionName: ./Implyzer.slnx
      ProjectPath: ./Implyzer/Implyzer/Implyzer.csproj
      TestProjectPath: ./Implyzer/Implyzer.Tests/Implyzer.Tests.csproj

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Restore dependencies
        run: dotnet restore ${{ env.SolutionName }} --ignore-failed-sources

      - name: Build project
        run: dotnet build ${{ env.ProjectPath }} --no-restore

      - name: Build test project
        run: dotnet build ${{ env.TestProjectPath }} --no-restore

      - name: Execute unit tests
        run: dotnet test ${{ env.TestProjectPath }} --no-build

      - name: Restore the application
        run: dotnet restore ${{ env.TestProjectPath }}